name: Hello
description: say hello world to target
inputs:
  name:
    description: target name
    required: true
outputs:
  target:
    value: ${{ inputs.name }}
    description: target name
runs:
  using: composite
  steps:
    - run: echo "Hello world, ${{name}}!"
      shell: bash
      env:
        name: ${{inputs.name}}
